#!/bin/bash

# variables
backupPath="/srv/backup/mongo" # duong dan backup cho mongodb
database=admin # ten database mongo can backup
mongodbUser=quang # mongodb user has access to backup database
mongodbPassword=quang # mongodb password for $mongodbUser
container=b7 # ten mongodb container
gdriveID=1s-404JX8xXET4iWZ2tGxyi8R3P7GFGVc
dateFormat=$(date '+%Y-%m-%d')
interface="ens33"
fileNum=$(ls $backupPath | wc -l)

# oldest dir of backupPath
oldestFile=$(find $backupPath -type f | sort | head -n 1)

if [[ $fileNum -ge 1 ]]; then
  rm -f $oldestFile
fi

# gen backup folder in container
docker exec -i $container /usr/bin/mongodump --username $mongodbUser --password $mongodbPassword --authenticationDatabase $database --db $database --out /dump

# copy backup folder to host
existPath=$backupPath/"$database"_"$dateFormat"
mkdir $existPath
docker cp $container:/dump/$database $existPath
cd "$backupPath" && tar -czf "$database"_"$dateFormat.tar.gz" "$database"_"$dateFormat" && rm -rf "$existPath"

# gen info for telemessage
existFile=$backupPath/"$database"_"$dateFormat".tar.gz
size=$(ls -lhrt $existFile | awk '{print $5}')

ip=$(/usr/sbin/ifconfig $interface | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')

message="Backup Failed!!!"$'\n'"Time: $dateFormat"
# gen telemessage
if [[ -e "$existFile" ]]; then
  date="$(date +"%e %b %Y, %a %r")"
  sync="$(/usr/local/bin/gdrive sync upload --keep-local --delete-extraneous --no-progress $backupPath $gdriveID | tail -1)"
  message="Backup successfully!!!"$'\n'"Address: $ip"$'\n'"Type: mongodb"$'\n'"Database: $database"$'\n'"Path: $existFile"$'\n'"Size: $size"$'\n'"Time: $dateFormat"$'\n'"$sync"
fi

# send notify
sh /srv/bkscript/telegram-send.sh "$message"
